import { type NextPage } from "next";
import Image from "next/image";
import Head from "next/head";
import { useEffect, useState } from "react";
import Navbar from "./components/Navbar";

type Company = {
  _id: string;
  company_name: string;
  location: string;
  website: string;
  logo_image_url: string;
  review_count: number;
  interview_count: number;
  difficult_rating: number;
  acceptance_rate: number;
  offer_count: number;
  common_job_posts: string[];
};

type ReviewDesc = {
  desc: string;
  questions: string[];
  _id: string;
};

type Review = {
  _id: string;
  user_id: string;
  company_id: string;
  job_title: string;
  interview_date: string;
  review: ReviewDesc;
  positive_flag: boolean;
  job_offer_flag: boolean;
  difficulty_rating: number;
  created_date: string;
  modified_date: string;
};

const Home: NextPage = () => {
  const [companyData, setCompData] = useState<Company[]>([]);
  const [reviews, setReviews] = useState<Review[]>([]);

  useEffect(() => {
    if (process.env.NEXT_PUBLIC_BACKEND_URL !== undefined) {
      fetch(`${process.env.NEXT_PUBLIC_BACKEND_URL}/api/companies`)
        .then((res) => res.json())
        .then((data: Company[]) => {
          setCompData(data);
        })
        .catch((err) => {
          console.log(err);
        });

      fetch(`${process.env.NEXT_PUBLIC_BACKEND_URL}/api/interviews`)
        .then((res) => res.json())
        .then((data: Review[]) => {
          setReviews(data);
        })
        .catch((err) => {
          console.log(err);
        });
    }
  }, []);

  // console.log(companyData);
  // console.log(reviews);

  // const companies = [
  //   { name: "RBC", color: "bg-blue-300" },
  //   { name: "TD", color: "bg-green-500" },
  //   { name: "BMO", color: "bg-blue-500" },
  //   { name: "CIBC", color: "bg-red-500" },
  //   { name: "Scotiabank", color: "bg-yellow-500" },
  //   { name: "BlacBerry", color: "bg-slate-800" },
  //   { name: "Nokia", color: "bg-blue-400" },
  //   { name: "Rogers", color: "bg-red-400" },
  //   { name: "Telus", color: "bg-green-400" },
  // ];

  // const reviews = [
  //   {
  //     name: "John Doe",
  //     position: "Software Engineer",
  //     company: "RBC",
  //     review:
  //       "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod. Lorem ipsum dolor sit amet consectetur",
  //   },
  //   {
  //     name: "Alex Doe",
  //     position: "Software Developer",
  //     company: "TD",
  //     review:
  //       "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod. Lorem ipsum dolor sit amet consectetur",
  //   },
  //   {
  //     name: "bob green",
  //     position: "AI Engineer",
  //     company: "BMO",
  //     review:
  //       "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod. Lorem ipsum dolor sit amet consectetur",
  //   },
  //   {
  //     name: "Alana gorgeous",
  //     position: "Data Scientist",
  //     company: "CIBC",
  //     review:
  //       "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod. Lorem ipsum dolor sit amet consectetur",
  //   },
  // ];

  return (
    <>
      <Navbar />
      <Head>
        <title>Lancer&apos;s View</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="mx-10 my-10 flex space-x-4">
          {companyData.map((company) => (
            <div
              key={company.company_name}
              className={
                "flex h-32  w-1/6 items-center justify-evenly  rounded-xl bg-gradient-to-t p-3	text-base text-gray-600 shadow-xl"
              }
            >
              <Image
                src={company.logo_image_url}
                // width={60}
                // height={52}
                alt={""}
                width="0"
                height="0"
                sizes="100vw"
                className="h-auto w-3/6"
              />
              <div className="p-4">{company.company_name}</div>
            </div>
          ))}
        </div>
        <div className="mx-10 space-y-4">
          {reviews.map((review) => (
            <div
              key={review._id}
              className="w-8/12 rounded-xl border border-gray-100 p-4 pl-4 shadow-lg"
            >
              <div className="space-x-2">
                <span className="text-lg font-semibold">
                  Anonoumous
                  {/* {review.user_id} */}
                </span>
                <span>{review.job_title}</span>
                {/* <span>{review.company}</span> */}
              </div>
              <div className="text-gray-500">{review.review.desc}</div>
            </div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
